FROM multiarch/alpine:armhf-v3.12

RUN apk add --no-cache curl ca-certificates

COPY duckdns-cron /etc/cron.d/duckdns-cron
RUN chmod 0644 /etc/cron.d/duckdns-cron
RUN crontab /etc/cron.d/duckdns-cron

COPY duckdns.sh /usr/local/bin/duckdns
RUN chmod 0700 /usr/local/bin/duckdns

ENTRYPOINT ["crond", "-f"]

# Metadata
ARG VCS_REF="Unknown"
LABEL maintainer="adsb@thebiggerguy.net" \
      org.label-schema.name="Docker ADS-B - DuckDNS" \
      org.label-schema.description="Docker container for ADS-B - This is the duckdns.com component" \
      org.label-schema.url="https://github.com/TheBiggerGuy/docker-ads-b" \
      org.label-schema.vcs-ref="${VCS_REF}" \
      org.label-schema.vcs-url="https://github.com/TheBiggerGuy/docker-ads-b" \
      org.label-schema.schema-version="1.0"
