FROM multiarch/debian-debootstrap:armhf-buster-slim as base

RUN apt-get update && \
    # Install required tools for gpg imports
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends apt-transport-https ca-certificates dirmngr gnupg && \
    # Install Mono Key
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF && \
    # Install Microsoft Key
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys BC528686B50D79E339D3721CEB3E94ADBE1229CF && \
    # Add Mono repo
    echo 'deb https://download.mono-project.com/repo/debian stable-stretch main' | tee /etc/apt/sources.list.d/mono-official-stable.list && \
    # Add Microsoft repo
    echo 'deb https://packages.microsoft.com/debian/9/prod stretch main'         | tee /etc/apt/sources.list.d/microsoft-official-stable.list && \
    # Remove the gpg tools
    apt-get remove --purge --autoremove -y gnupg dirmngr && \
    # Update to pick up new repos
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends curl ca-certificates iputils-ping \
        mono-runtime \
        cli-common \
        binfmt-support \
        ca-certificates-mono \
        libmono-sqlite4.0-cil \
        libmono-system2.0-cil \
        libmono-system4.0-cil \
        libmono-security4.0-cil \
        libmono-windowsbase4.0-cil \
        libmono-system-componentmodel-dataannotations4.0-cil \
        libmono-system-core4.0-cil \
        libmono-system-configuration4.0-cil \
        libmono-system-data4.0-cil \
        libmono-system-data-datasetextensions4.0-cil \
        libmono-system-deployment4.0-cil \
        libmono-system-design4.0-cil \
        libmono-system-drawing4.0-cil \
        libmono-system-enterpriseservices4.0-cil \
        libmono-system-io-compression4.0-cil \
        libmono-system-net4.0-cil \
        libmono-system-net-http4.0-cil \
        libmono-system-runtime4.0-cil \
        libmono-system-runtime-serialization4.0-cil \
        libmono-system-security4.0-cil \
        libmono-system-servicemodel4.0a-cil \
        libmono-system-servicemodel-web4.0-cil \
        libmono-system-transactions4.0-cil \
        libmono-system-web4.0-cil \
        libmono-system-web-services4.0-cil \
        libmono-system-windows4.0-cil \
        libmono-system-windows-forms4.0-cil \
        libmono-system-xml4.0-cil \
        libmono-system-xml-linq4.0-cil \
        libmono-system-xml-serialization4.0-cil && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

FROM base as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends mono-devel msbuild nuget

ARG VIRTUALRADAR_VERSION
ARG VIRTUALRADAR_HASH

RUN curl --output VirtualRadar.tar.gz -L "https://github.com/vradarserver/vrs/archive/${VIRTUALRADAR_VERSION}.tar.gz" && \
    sha256sum VirtualRadar.tar.gz && echo "${VIRTUALRADAR_HASH}  VirtualRadar.tar.gz" | sha256sum -c

RUN mkdir vrs && cd vrs && \
    tar -xvf ../VirtualRadar.tar.gz --strip-components=1
WORKDIR vrs

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends dotnet-sdk-2.1

RUN nuget install Microsoft.Owin
RUN msbuild

# COPY VirtualRadar.exe.config /vrs/VirtualRadar.exe.config

FROM base

COPY --from=builder /vrs /opt/vrs

COPY InstallerConfiguration.xml /root/.local/share/VirtualRadar/InstallerConfiguration.xml
COPY Configuration.xml /root/.local/share/VirtualRadar/Configuration.xml
COPY vrs-runner.sh /usr/local/bin/vrs-runner

EXPOSE 30053

HEALTHCHECK --start-period=1m --interval=30s --timeout=5s --retries=3 CMD curl --fail http://localhost:8080/VirtualRadar/ || exit 1

ENTRYPOINT ["vrs-runner"]

# Metadata
ARG VCS_REF="Unknown"
LABEL maintainer="thebigguy.co.uk@gmail.com" \
      org.label-schema.name="Docker ADS-B - VirtualRadar" \
      org.label-schema.description="Docker container for ADS-B - This is the virtualradarserver.co.uk component" \
      org.label-schema.url="https://github.com/TheBiggerGuy/docker-ads-b" \
      org.label-schema.vcs-ref="${VCS_REF}" \
      org.label-schema.vcs-url="https://github.com/TheBiggerGuy/docker-ads-b" \
      org.label-schema.schema-version="1.0"
